// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grlawnzcsrumnyzcziqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybGF3bnpjc3J1bW55emN6aXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk3MDQsImV4cCI6MjA2NTU4NTcwNH0.brgjXi1WKvIh1Luk_t0g-jJ-uVlAJPxY8Y6-sC-S0_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);